seed: 42
device: cuda:0
num_steps_per_env: 24
max_iterations: 35000
policy:
  class_name: EncoderActorCritic
  init_noise_std: 1.0
  actor_hidden_dims:
  - 512
  - 256
  - 128
  critic_hidden_dims:
  - 512
  - 256
  - 128
  activation: elu
  num_moe_experts: null
  moe_gate_hidden_dims: null
  encoder_configs:
    depth_image:
      class_name: Conv2dHeadModel
      component_names:
      - depth_image
      output_size: 32
      takeout_input_components: true
      channels:
      - 32
      - 32
      kernel_sizes:
      - 3
      - 3
      strides:
      - 1
      - 1
      hidden_sizes:
      - 32
      paddings:
      - 1
      - 1
      nonlinearity: ReLU
      use_maxpool: false
  critic_encoder_configs: null
  vae_encoder_kwargs: null
  vae_decoder_kwargs: null
  vae_latent_size: null
  vae_input_subobs_components: null
  vae_aux_subobs_components: null
algorithm:
  class_name: PPO
  value_loss_coef: 1.0
  use_clipped_value_loss: true
  clip_param: 0.2
  entropy_coef: 0.005
  num_learning_epochs: 5
  num_mini_batches: 4
  learning_rate: 0.001
  optimizer_class_name: AdamW
  schedule: adaptive
  gamma: 0.99
  lam: 0.95
  advantage_mixing_weights: 1.0
  desired_kl: 0.01
  max_grad_norm: 1.0
  clip_min_std: 1.0e-12
  kl_loss_func: null
  kl_loss_coef: null
  using_ppo: null
  teacher_policy_class_name: null
  teacher_policy: null
  teacher_logdir: null
  label_action_with_critic_obs: null
  teacher_act_prob: null
  update_times_scale: null
  distillation_loss_coef: null
  distill_target: null
  actor_state_key: null
  reference_state_key: null
  discriminator_class_name: null
  discriminator_kwargs: null
  discriminator_optimizer_class_name: null
  discriminator_optimizer_kwargs: null
  discriminator_reward_coef: null
  discriminator_reward_type: null
  discriminator_loss_func: null
  discriminator_loss_coef: null
  discriminator_gradient_penalty_coef: null
  discriminator_weight_decay_coef: null
  discriminator_logit_weight_decay_coef: null
  discriminator_gradient_torlerance: null
  discriminator_backbone_gradient_only: null
normalizers:
  policy:
    class_name: EmpiricalNormalization
  critic:
    class_name: EmpiricalNormalization
save_interval: 1000
log_interval: 10
experiment_name: g1_perceptive_shadowing
run_name: ''
resume: true
load_run: /home/duanxin/Xyk/Project-Instinct/Instinct_MJ/logs/instinct_rl/g1_perceptive_shadowing/2026-03-07_15-29-45/
load_checkpoint: model_58000.pt
ckpt_manipulator: null
ckpt_manipulator_kwargs: {}
policy_observation_group: policy
critic_observation_group: critic
